### ISSUE TITLE
transform-runtime plugin dependency

### ISSUE THREAD

**Issue by blackfyre** [NightCatSama/vue-slider-component#43]
I've just pulled this into an existing project, and this is the first error:

```
 error  in ./~/vue-slider-component/dist/index.js

Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "C:\\projects\\vpt\\node_modules\\vue-slider-component\\.babelrc" at 0, attempted to resolve relative to "C:\\projects\\vpt\\node_modules\\vue-slider-component"
    at C:\projects\vpt\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (C:\projects\vpt\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\projects\vpt\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\projects\vpt\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\projects\vpt\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\projects\vpt\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\projects\vpt\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\projects\vpt\node_modules\babel-loader\lib\index.js:46:20)
    at C:\projects\vpt\node_modules\babel-loader\lib\fs-cache.js:79:18
    at ReadFileContext.callback (C:\projects\vpt\node_modules\babel-loader\lib\fs-cache.js:15:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:358:13)
```

The build env is Windows 10, and running webpack bundler

**Comment by blackfyre** [comment]
Nothing much to tell, this was thrown by the vue 2 snippet you have shared.
Porbably because we use `.vue` files and pre-compile it.

**Comment by NightCatSama** [comment]
You can try to use 
```js
import vueSlider form 'vue-slider-component/src/vue2-slider.vue'
```

**Comment by blackfyre** [comment]
That was the first thing I tried, the result is the same.

**Comment by NightCatSama** [comment]
Would you run `npm run build` on `vue-slider-component`?

If so, make sure the `babel-plugin-transform-runtime` is already installed completely.
