### ISSUE TITLE
After updating to 3.2.20 from 2.8.16, the bar is not visible and it throws an error when I click on where the slider should be

### ISSUE THREAD

**Issue by DoctorNo124** [NightCatSama/vue-slider-component#645]
Hello all, 

Only the dots are visible and the bar is not visible. However, I can't move the dots whatsoever. When I click on where the bar should be, I get the following error: 

vue.esm.js:3736 TypeError: Cannot read properties of undefined (reading 'disabled')
    at VueComponent.value (vue-slider-component.umd.min.js:6:37884)
    at VueComponent.value (vue-slider-component.umd.min.js:6:37113)
    at invokeWithErrorHandling (vue.esm.js:3704:1)
    at HTMLDivElement.invoker (vue.esm.js:1524:1)
    at original_1._wrapper (vue.esm.js:7968:1)

Here is how it looks: 
![slider not working](https://user-images.githubusercontent.com/29240797/192044851-c580e0ca-ff77-4abb-8bdc-9eba1541a184.PNG)

Thanks,
Noah

**Comment by DoctorNo124** [comment]
I realized why the bar wasn't visible - I was passing 6 as a string to the height property, where I should have been passing '6px' as a string. Still having the issue where I can't drag the dots, however.

**Comment by DoctorNo124** [comment]
More information - so, starting out on this page, I pass disabled as true to the slider component, so it starts out disabled. I pass disabled as false later on, but it doesn't allow the dots to be dragged.

**Comment by NightCatSama** [comment]
Please provide an online example.
