### ISSUE TITLE
TypeError: S.extend is not a function (incompatible with Vue 2.7.0)

### ISSUE THREAD

**Issue by erikbjoern** [NightCatSama/vue-slider-component#687]
#### Describe the bug
Importing the component breaks the whole module where it is used.

#### Stack trace
I receive the following error in the console:
```
index-ad485ea7.js:4423 TypeError: S.extend is not a function
    at $ (Index-da365524.js:10:2400)
    at Index-da365524.js:10:2848
    at h (Index-da365524.js:10:6956)
    at Index-da365524.js:10:11721
    at Module.fb15 (Index-da365524.js:10:11757)
    at d (Index-da365524.js:1:598)
    at 091b (Index-da365524.js:1:1379)
    at Index-da365524.js:1:1393
    at Index-da365524.js:1:439
    at Index-da365524.js:1:446
```

#### Environment (If you feel unrelated, please delete the block)
 - Vue version: v2.7
 - Component Version: v3.2.24

**Comment by erikbjoern** [comment]
Almost identical problem reported in #663
